---
title: "Who wants to come to the US?"
author: "Steven Herrera"
date: "4/16/2019"
output: html_document
---

### Loading packages

```{r}
library(tidyverse)
```


## Using the GDP data 

Below, we will use GDP per capita data from the World Bank website:

```{r}
gdp <- read.csv("gdp.csv")
```


Here is the link for the information: <https://data.worldbank.org/indicator/ny.gdp.pcap.cd>

```{r}
gdp <- gdp %>%
  mutate(year_group = case_when(
    Year >= 1960 & Year < 1970 ~ "1960s",
    Year >= 1970 & Year < 1980 ~ "1970s",
    Year >= 1980 & Year < 1990 ~ "1980s",
    Year >= 1990 & Year < 2000 ~ "1990s",
    Year >= 2000 & Year < 2010 ~ "2000s",
    Year >= 2010 & Year < 2017 ~ "2010s",
  )) 
```


### Mexico vs US

```{r}
only_mex <- gdp %>%
  select(Mexico, Year, year_group) %>%
  mutate(mex_or_nah = "Mexico",
         toget = Mexico) %>%
  select(toget, Year, year_group, mex_or_nah)

only_us <- gdp %>%
  select(United.States, Year, year_group) %>%
  mutate(mex_or_nah = "United States",
         toget = United.States) %>%
  select(toget, Year, year_group, mex_or_nah)

us_and_mex <- rbind(only_us, only_mex)
```


```{r}
ggplot(us_and_mex, mapping = aes(x = Year, y = toget, fill = mex_or_nah)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(title = "Understanding the Difference in GDP Per Capita",
       subtitle = "Between Mexico and the United States",
       x = "Years 1960 - 2017",
       y = "GDP (per capita)",
       fill = "Country")
```

### Somalia

```{r}
only_som <- gdp %>%
  select(Somalia, Year, year_group) %>%
  mutate(som_or_nah = "Somalia",
         toget = Somalia) %>%
  select(toget, Year, year_group, som_or_nah)

only_us_som <- gdp %>%
  select(United.States, Year, year_group) %>%
  mutate(som_or_nah = "United States",
         toget = United.States) %>%
  select(toget, Year, year_group, som_or_nah)

us_and_som <- rbind(only_us_som, only_som)
```

```{r}
ggplot(us_and_som, mapping = aes(x = Year, y = toget, fill = som_or_nah)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(title = "Understanding the Difference in GDP Per Capita",
       subtitle = "Between Somalia and the United States",
       x = "Years 1960 - 2017",
       y = "GDP (per capita)",
       fill = "Country")
```


### Myanmar

```{r}
only_myan <- gdp %>%
  select(Myanmar, Year, year_group) %>%
  mutate(myan_or_nah = "Myanmar",
         toget = Myanmar) %>%
  select(toget, Year, year_group, myan_or_nah)

only_us_myan <- gdp %>%
  select(United.States, Year, year_group) %>%
  mutate(myan_or_nah = "United States",
         toget = United.States) %>%
  select(toget, Year, year_group, myan_or_nah)

us_and_myan <- rbind(only_us_myan, only_myan)
```

```{r}
ggplot(us_and_myan, mapping = aes(x = Year, y = toget, fill = myan_or_nah)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(title = "Understanding the Difference in GDP Per Capita",
       subtitle = "Between Myanmar and the United States",
       x = "Years 1960 - 2017",
       y = "GDP (per capita)",
       fill = "Country")
```

### Iraq

```{r}
only_iraq <- gdp %>%
  select(Iraq, Year, year_group) %>%
  mutate(iraq_or_nah = "Iraq",
         toget = Iraq) %>%
  select(toget, Year, year_group, iraq_or_nah)

only_us_iraq <- gdp %>%
  select(United.States, Year, year_group) %>%
  mutate(iraq_or_nah = "United States",
         toget = United.States) %>%
  select(toget, Year, year_group, iraq_or_nah)

us_and_iraq <- rbind(only_us_iraq, only_iraq)
```

```{r}
ggplot(us_and_iraq, mapping = aes(x = Year, y = toget, fill = iraq_or_nah)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(title = "Understanding the Difference in GDP Per Capita",
       subtitle = "Between Iraq and the United States",
       x = "Years 1960 - 2017",
       y = "GDP (per capita)",
       fill = "Country")
```

### Iran

```{r}
only_iran <- gdp %>%
  select(Iran..Islamic.Rep., Year, year_group) %>%
  mutate(iran_or_nah = "Iran",
         toget = Iran..Islamic.Rep.) %>%
  select(toget, Year, year_group, iran_or_nah)

only_us_iran <- gdp %>%
  select(United.States, Year, year_group) %>%
  mutate(iran_or_nah = "United States",
         toget = United.States) %>%
  select(toget, Year, year_group, iran_or_nah)

us_and_iran <- rbind(only_us_iran, only_iran)
```

```{r}
ggplot(us_and_iran, mapping = aes(x = Year, y = toget, fill = iran_or_nah)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  theme_minimal() +
  labs(title = "Understanding the Difference in GDP Per Capita",
       subtitle = "Between Iran and the United States",
       x = "Years 1960 - 2017",
       y = "GDP (per capita)",
       fill = "Country")
```




## Using the Mexico data:



```{r}
mexico <- read.csv("mexico_data.csv")
```








